server:
  host: 0.0.0.0
  port: 9999
database:
  driver: mysql
  host: localhost
  port: 12006
  user: root
  password: abc123456
  db: emos
  migration: auto

jwt:
  secret: emos_jwt_secret
  issuer: phos