server:
  host: 0.0.0.0
  port: 9999

database:
  driver: mysql
  host: localhost
  port: 12006
  user: root
  password: abc123456
  db: emos
  # migration: auto

mongodb:
  host: localhost
  port: 27017
  user: admin
  password: abc123456
  max-pool-size: 20

redis:
  host: localhost
  port: 6379
  password: abc123456
  db: 0


jwt:
  secret: go_bootstrap_jwt_secret
  issuer: phos